import { FC } from 'react';
import Head from 'next/head';

import { layoutProps } from 'utils/type';

const Layout: FC<layoutProps> = ({ children, title}) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {children}
        </>
    )
}

export default Layout