import { FC } from 'react'
import Head from 'next/head'

import { Navigation } from '@components/Navigation'
import { Footer } from '@components/Footer'
import { layoutProps } from '@utils/type'

const Layout: FC<layoutProps> = ({ children, title}) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <body>
                <noscript>
                    You need to enable JavaScript to run this app.
                </noscript>
                <Navigation />
                <main className='container'>
                    {children}
                </main>
                <Footer />
            </body>
        </>
    )
}

export default Layout