import { FC } from 'react'
import Head from 'next/head'

import { Navigation } from '@components/Navigation'
import { Footer } from '@components/Footer'
import { layoutProps } from '@utils/type'
import styled from 'styled-components'

const Body = styled.body`
    display: flex;
    height: 100vh;
    flex-direction: column;
    --tw-bg-opacity: 1;
    background-color: rgb(245 245 250 / var(--tw-bg-opacity));
    font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
    transition: filter 400ms;    
`

const Layout: FC<layoutProps> = ({ children, title}) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Body>
                <noscript>
                    You need to enable JavaScript to run this app.
                </noscript>
                <Navigation />
                <main className='container'>
                    {children}
                </main>
                <Footer />
            </Body>
        </>
    )
}

export default Layout